[package]
name = "player"
version = "0.1.0"
edition = "2021"

[lib]
name = "player"
path = "src/player.rs"

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking"] }
quick-xml = {version ="0.37.2", features = [ "serialize" ] }
serde = { version = "1.0", features = ["derive"] }
iso8601-duration = { version = "0.2" }
url = { version = "2.5.4" }
tokio = { version = "1.43.0", features = ["full"] }
re_mp4 = { version = "0.3.0" }
ffmpeg-next = { version = "7.1.0"}
ffmpeg-sys-next = { version = "7.1.0"}
hex = { version = "0.4" }
cpal ={ version =  "0.15.3" }
bytemuck ={ version =  "1.13.1" }
pollster = "0.4.0"
wgpu = "24.0.1"
winit = "0.30.9"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.60.0", features = [
    "Win32_System_Com", 
    "Win32_System_Console", 
    "Win32_System_SystemServices", 
    "Win32_UI_Shell", 
    "Win32_Foundation",
    "Win32_Graphics_Dwm", 
    "Win32_Graphics_Direct3D", 
    "Win32_Graphics_Direct3D9", 
    "Win32_Graphics_Direct3D11", 
    "Win32_Graphics_Dxgi_Common", 
    "Win32_Graphics_Dxgi", 
    "Win32_Security"] }
